### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by wavymate** [torch2424/live-stream-radio#102]
I get this error when starting the stream: https://imgur.com/0JGPs8C

`ffmpeg stderr:

 ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'stream_loop'.
Error splitting the argument list: Option not found

ffmpeg stdout:

ffmpeg err:

 Error: ffmpeg exited with code 1: Unrecognized option 'stream_loop'.
Error splitting the argument list: Option not found

    at ChildProcess.<anonymous> (/usr/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

ffmpeg encountered an error. 😨
Please see the stderror output above to fix the issue.
`

**Comment by AndreasWebdev** [comment]
`ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers`

Seems like you have built your own binaries or installed them from apt. Try using the ffmpeg binaries from here https://torch2424.github.io/live-stream-radio/#/cli/getting-started

**Comment by torch2424** [comment]
@AndreasWebdev Couldn't have said it better myself! 😄

**Comment by AndreasWebdev** [comment]
@wavymate can you try using these ffmpeg binaries? They are proven to work with this project: https://github.com/torch2424/live-stream-radio/releases/tag/ffmpeg-builds

**Comment by wavymate** [comment]
How would I install it?

**Comment by AndreasWebdev** [comment]
there mare multiple ways to do it, I personally just unpacked the binaries in a /bin folder of my project

![image](https://user-images.githubusercontent.com/7365286/48055696-7e0bdb00-e1b0-11e8-9ec9-d3d2ba04f954.png)

and set the `ffmpeg_path` config

![image](https://user-images.githubusercontent.com/7365286/48055728-90861480-e1b0-11e8-9eb7-627d4c6502c3.png)

**Comment by wavymate** [comment]
I'm a little confused, am I able to email you so you can configure this the proper way?

**Comment by AndreasWebdev** [comment]
Sure I can help you! you can reach me through discord (iKlikla#4975) or email (privat AT andreas-heimann DOT com)
