### ISSUE TITLE
Audio & Video directory [Support]

### ISSUE THREAD

**Issue by orophix** [torch2424/live-stream-radio#103]
inside config.json:

```
 "radio": {
    "audio_directory": "mnt/streamstorage/music/chillstation/",
    "video_directory": "mnt/streamstorage/video/chillstation",
```

Output:

```
(node:24226) UnhandledPromiseRejectionWarning: Error: **/home/stream1/chillstation/**mnt/streamstorage/music/chillstation/ does not exist.
    at Object.notExist (/usr/local/lib/node_modules/live-stream-radio/node_modules/find/index.js:41:12)
    at traverseSync (/usr/local/lib/node_modules/live-stream-radio/node_modules/find/index.js:224:38)
    at Object.find.(anonymous function) [as fileSync] (/usr/local/lib/node_modules/live-stream-radio/node_modules/find/index.js:374:5)
```
Why is it forcing it to read the home path etc.. ?

**Comment by AndreasWebdev** [comment]
can you try to add a foreslash infront of the mnt? It seems as it's trying to just append your path to your working directory.

`**/home/stream1/chillstation/**mnt/streamstorage/music/chillstation/`

**Comment by AndreasWebdev** [comment]
Also, does the fs loading even accept absolute paths? I am not sure on this @torch2424

**Comment by dropitlikecross** [comment]
Has this been updated yet @torch2424 or do I still need to use symbolic links?

**Comment by torch2424** [comment]
@dropitlikecross (nice username), unfortunately haven't had time for the project because of my WASM Gameboy thing, and Kingdom Hearts 3. 😞 

If possible use Symbolic links for now. Thanks! 😄
