### ISSUE TITLE
Error did not find a config.json

### ISSUE THREAD

**Issue by dropitlikecross** [torch2424/live-stream-radio#112]
Hello,

Some issues trying to start the stream.

Generated as gamingstream. Correct location for config.json should be /home/stream1/gamingstream/ but it's added an extra directory.

```
error did not find a config.json at: /home/stream1/gamingstream/gamingstream/config.json 😞
/home/stream1/.nvm/versions/node/v10.15.1/lib/node_modules/live-stream-radio/src/index.js:117
  console.log(e.message);

ReferenceError: e is not defined
    at Object.<anonymous> (/home/stream1/.nvm/versions/node/v10.15.1/lib/node_modules/live-stream-radio/src/index.js:117:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)


```

**Comment by AndreasWebdev** [comment]
Hello, from which directory are you calling the livestreamradio command?

**Comment by dropitlikecross** [comment]
Ah got it. I was starting from within the folder, needed to start it from outside the folder.
Thank you!
