### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by Sumonil** [torch2424/live-stream-radio#118]
Hello, i have this error when i'm trying to start a stream:
ffmpeg err:

 Error: ffmpeg exited with code 1: Error initializing complex filters.
Invalid argument

    at ChildProcess.<anonymous> (/usr/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)

**Comment by torch2424** [comment]
Hello!

did you build your own binaries or installed them from apt? (the ones on apt are heavily outdated, you need at least ffmpeg 4.2.0). Try using the ffmpeg binaries from here https://torch2424.github.io/live-stream-radio/#/cli/getting-started

**Comment by torch2424** [comment]
@Sumonil Did you re-open this because my suggestions did not work? Or did you have more questions about this issue? 😄
