### ISSUE TITLE
Problem with installation (gifsicle)

### ISSUE THREAD

**Issue by tengufromsky** [torch2424/live-stream-radio#119]
I'm complete newbie in manual installation node.js programs.
But I already have a problem with `npm install -g live-stream-radio`:

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/home/nick/.nvm/versions/node/v10.15.3/bin/live-stream-radio -> /home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/src/index.js

> gifsicle@3.0.4 postinstall /home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/gifsicle
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/gifsicle/vendor'
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                ^

Error: callback() can only be called once.
    at onetime (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/onetime/index.js:15:11)
    at /home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:194:15)
    at finishMaybe (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/nick/.nvm/versions/node/v10.15.3/lib/node_modules/live-stream-radio/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at DuplexWrapper.emit (events.js:194:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

my system is Linux Manjaro (arch-based) and i already do `nvm install --lts`

**Comment by AndreasWebdev** [comment]
you should try running the npm command through sudo, it seems like you have no access to the global nvm/npm folder `⚠ EACCES: permission denied`

`sudo npm install -g live-stream-radio`

**Comment by tengufromsky** [comment]
Sorry, I forgot to say that I ran the installation command with `sudo`. This problem still exists.

**Comment by torch2424** [comment]
Hello!

So have you seen the CLI getting started?

https://torch2424.github.io/live-stream-radio/#/cli/getting-started

What you may want to do is try setting up nvm, and what I personally do is set up npm to not require sudo: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

This sets up npm to use a directory in my home folder, and I find that to be the easiest to manage.

Thanks! 😄
