### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dropitlikecross** [torch2424/live-stream-radio#130]
Just ran a fresh install and when I try to load I get:

`(node:57013) UnhandledPromiseRejectionWarning: Error: File not found: undefined
    at Object.<anonymous> (/home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/strtok3/lib/index.js:28:19)
    at Generator.next (<anonymous>)
    at /home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/strtok3/lib/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/strtok3/lib/index.js:3:12)
    at Object.fromFile (/home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/strtok3/lib/index.js:21:12)
    at Object.<anonymous> (/home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/music-metadata/lib/index.js:47:45)
    at Generator.next (<anonymous>)
    at /home/stream1/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/music-metadata/lib/index.js:7:71
    at new Promise (<anonymous>)
(node:57013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:57013) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Any ideas?

**Comment by AndreasWebdev** [comment]
Can you provide an output of your project folder?

**Comment by dropitlikecross** [comment]
Where's that kept @AndreasWebdev ?

**Comment by AndreasWebdev** [comment]
Did you generate a project as shown [here](https://torch2424.github.io/live-stream-radio/#/#generating-a-stream-project)

**Comment by dropitlikecross** [comment]
Yes, are you just after this? 
`audio  config.json  fonts  interludes  live-stream-radio-overlay-image.png  video
`

**Comment by dropitlikecross** [comment]
Turns out it doesn't like symbolic links in the audio and video folders.
