### ISSUE TITLE
ffmpeg error on start streaming 

### ISSUE THREAD

**Issue by magvay** [torch2424/live-stream-radio#134]
$ uname -a
Linux magvay-pc 5.2.11-1-MANJARO #1 SMP PREEMPT Thu Aug 29 07:41:24 UTC 2019 x86_64 GNU/Linux

$ live-stream-radio --start magstream
Using the config.json at: /home/magvay/magstream/config.json

API Started at: http://127.0.0.1:8000

████████████████████████████████████████████████████████████████████████████████████████

Starting stream! 🛠️

Streaming to: rtmp://a.rtmp.youtube.com/live2/r91q-g7pk-ruuv-0xuu

Finding audio... 🎤

Playing the audio:
/home/magvay/magstream/audio/Miata feat Of The Other Time.mp3

Finding/Optimizing video... 📺

Playing the video:
/home/magvay/magstream/video/publicDomainEarth.mp4

Artist: Marquice Turner
Album: little bytes ep
Song: Miata feat Of The Other Time
Duration (seconds): 165

 
Spawned Ffmpeg with command:
ffmpeg -stream_loop -1 -i /home/magvay/magstream/video/publicDomainEarth.mp4 -i /home/magvay/magstream/audio/Miata feat Of The Other Time.mp3 -f lavfi -re -i anullsrc -i /home/magvay/magstream/live-stream-radio-overlay-image.png -filter_complex [1:a] adelay=3000|3000 [delayedaudio]; [delayedaudio][2:a] amix=inputs=2:duration=first:dropout_transition=3 [audiooutput]; [audiooutput] loudnorm [audiooutput]; [0:v] fps=fps=24 [inputvideo];[3:v][inputvideo] scale2ref [scaledoverlayimage][scaledvideo];[scaledvideo][scaledoverlayimage] overlay=x=0:y=0, drawtext=text='Live Stream Radio, 24/7 Open Source Radio':fontfile=/home/magvay/magstream/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.05):x=w-mod(max(t\, 0) * (w + tw) / 20\, (w + tw)),drawtext=text='Artist: Marquice Turner':fontfile=/home/magvay/magstream/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.15):x=(w * 0.02),drawtext=text='Song: Miata feat Of The Other Time':fontfile=/home/magvay/magstream/./fonts/Lato-Regular.ttf:fontsize=(w * 0.03333333333333333):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.25):x=(w * 0.02) [videooutput] -acodec copy -acodec copy -map [videooutput] -map [audiooutput] -r 24 -g 48 -t 171 -pix_fmt yuv420p -x264-params keyint=48:min-keyint=48:scenecut=-1 -s 240x426 -b:v 500k -b:a 96k -ar 44100 -acodec mp3 -vcodec libx264 -preset superfast -bufsize 960k -crf 28 -threads 1 -f flv rtmp://a.rtmp.youtube.com/live2/r91q-g7pk-ruuv-0xuu
 
Audio Progress ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | Time Playing: 1s |

████████████████████████████████████████████████████████████████████████████████████████

ffmpeg stderr: 

 ffmpeg version N-50091-gfc20ba9e04-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.100 / 58. 59.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/magvay/magstream/video/publicDomainEarth.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-21T02:37:57.000000Z
  Duration: 00:00:24.01, start: 0.000000, bitrate: 1315 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1185 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2016-08-21T02:37:57.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-08-21T02:37:57.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #1, mp3, from '/home/magvay/magstream/audio/Miata feat Of The Other Time.mp3':
  Metadata:
    album           : little bytes ep
    artist          : Marquice Turner
    album_artist    : Marquice Turner
    genre           : Electronic
    title           : Miata feat Of The Other Time
    track           : 5
    Software        : FL Studio 12
    date            : 2018
  Duration: 00:02:44.62, start: 0.025056, bitrate: 320 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.99r
    Stream #1:1: Video: png, pal8(pc), 2400x2400, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
Input #2, lavfi, from 'anullsrc':
  Duration: N/A, start: 0.000000, bitrate: 705 kb/s
    Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
Input #3, png_pipe, from '/home/magvay/magstream/live-stream-radio-overlay-image.png':
  Duration: N/A, bitrate: N/A
    Stream #3:0: Video: png, rgba(pc), 854x480, 25 tbr, 25 tbn, 25 tbc

ffmpeg stdout: 

 
ffmpeg err: 

 Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/home/magvay/.nvm/versions/node/v10.16.3/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

ffmpeg encountered an error. 😨
Please see the stderror output above to fix the issue.

![image](https://user-images.githubusercontent.com/7048057/65947349-4c53d080-e462-11e9-9776-78e80b13c488.png)

**Comment by AndreasWebdev** [comment]
Hey there, none one the "common" problems people have.

A SIGSEGV indicates that something is accessing memory wrong, it's a segmentation fault error. My gut feeling tells me, that the FFMPEG nightly build you used has a bug which throws this. From your error log I can see that the SIGSEGV appears in the fluent-ffmpeg connection, so there is nothing wrong with your live-stream-radio install.

**Comment by AndreasWebdev** [comment]
Checked around in the ffmpeg bugtracker and found this, might be related: https://trac.ffmpeg.org/ticket/8181

**Comment by torch2424** [comment]
Thanks! @AndreasWebdev 😄

**Comment by kylejbrk** [comment]
Any updates here? I am having the same issue.

**Comment by SyntaxisCS** [comment]
What was the fix? I'm getting this same exact error and I have no idea how to fix it.
