### ISSUE TITLE
EACCES Error

### ISSUE THREAD

**Issue by oddnebula** [torch2424/live-stream-radio#137]
Hi, I've been trying to setup a live stream for a while now but whenever I try to start it I get the following error:

ffmpeg stderr: 

 undefined
ffmpeg stdout: 

 undefined
ffmpeg err: 

 Error: spawn /home/pi/Downloads/live-stream-radio-ffmpeg-builds EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /home/pi/Downloads/live-stream-radio-ffmpeg-builds',
  path: '/home/pi/Downloads/live-stream-radio-ffmpeg-builds',
  spawnargs: [ '-formats' ]
}

ffmpeg encountered an error. 😨
Please see the stderror output above to fix the issue.

I'm on a Raspberry Pi 4 and have tried using the pre-compiled builds and tried compiling my own. I'm still very new to this so help would be greatly appreciated!

**Comment by AndreasWebdev** [comment]
Please confirm that the ffmpeg build is executable. You can do that by running `sudo chmod +x FILE` where FILE refers to the ffmpeg build.

**Comment by torch2424** [comment]
@oddnebula Did @AndreasWebdev suggestion work for you? Can we close this issue? :smile: Let us know if so! Thanks!

**Comment by AndreasWebdev** [comment]
Closing this issue as there is no activity in here.

Feel free to open another issue if the problem persists!
