### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by bboymega** [torch2424/live-stream-radio#173]
Finding/Optimizing video... 📺

(node:108321) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'endsWith' of undefined
    at getVideo (/root/live-stream-radio/src/stream/stream.js:40:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/root/live-stream-radio/src/stream/stream.js:93:25)
    at async Object.start (/root/live-stream-radio/src/stream/index.js:97:5)
(node:108321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by torch2424** [comment]
@M3GABOY Hello! So, this seems like you may have an error with your config. I'd maybe start again from a fresh config: https://github.com/torch2424/live-stream-radio/blob/master/src/generate/template/config.json

Also, feel free to look at documentation here: https://torch2424.github.io/live-stream-radio/#/
