### ISSUE TITLE
Unable to Find Proper Binaries

### ISSUE THREAD

**Issue by kylejbrk** [torch2424/live-stream-radio#176]
I was following the instructions but am getting tripped up on how to download the binaries needed for ffmpeg.

The instructions say to go to this mock release: https://github.com/torch2424/live-stream-radio/releases/tag/ffmpeg-builds
But I am unable to find the actual binaries in the assets. 

I also tried using the alternative binaries listed here: https://johnvansickle.com/ffmpeg/
But this results with the following error:
```

ffmpeg err: 

 Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/home/kyle/.nvm/versions/node/v14.17.6/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

**Comment by kylejbrk** [comment]
Figured it out. My issue wasn't the binaries.

I accidentally changed the stream url in my config file. Once I corrected it everything worked fine.
