### ISSUE TITLE
Latest update broke Windows support

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#79]
Latest update (npm and repo master) broke Windows support again. I am very sure it's something about the paths again!

```
Playing the audio:
F:\Development\splatoon-music\interludes\audio\start.mp3


Finding/Optimizing video... 📺


Playing the video:
F:\Development\splatoon-music\interludes\video\title.mp4


Duration (seconds): 3



Spawned Ffmpeg with command:
ffmpeg -stream_loop -1 -i F\:\\Development\\splatoon-music\\interludes\\video\\title.mp4 -i F:\Development\splatoon-music\interludes\audio\start.mp3 -f lavfi -re -i anullsrc -i F\:/Development/splatoon-music/overlay.png -filter_complex [1:a] adelay=3000|3000 [delayedaudio]; [delayedaudio][2:a] amix=inputs=2:duration=first:dropout_transition=3 [audiooutput]; [0:v] fps=fps=30 [inputvideo];[3:v][inputvideo] scale2ref [scaledoverlayimage][scaledvideo];[scaledvideo][scaledoverlayimage] overlay=x=0:y=0, drawtext=text='Let\'s go!':fontfile=F:\Development/splatoon-music/./fonts/Splatfont2.ttf:fontsize=(w * 0.02):bordercolor=#000000:borderw=1:fontcolor=#FFFFFF:y=(h * 0.74):x=(w * 0.07) [videooutput] -acodec copy -acodec copy -map [videooutput] -map [audiooutput] -r 30 -g 60 -t 9 -pix_fmt yuv420p -x264-params keyint=60:min-keyint=60:scenecut=-1 -s 1280x720 -b:v 4500k -b:a 128k -ar 44100 -acodec aac -vcodec libx264 -preset medium -bufsize 960k -crf 28 -threads 3 -f flv rtmp://a.rtmp.youtube.com/live2/KEY

Audio Progress ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | Time Playing: 0s |


████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████


ffmpeg stderr:

 ffmpeg version N-92079-gb577153231 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180813
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 31.102 / 58. 31.102
  libavformat    58. 18.103 / 58. 18.103
  libavdevice    58.  4.104 / 58.  4.104
  libavfilter     7. 33.100 /  7. 33.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
F\:\\Development\\splatoon-music\\interludes\\video\\title.mp4: Invalid argument

ffmpeg stdout:


ffmpeg err:

 Error: ffmpeg exited with code 1: F\:\\Development\\splatoon-music\\interludes\\video\\title.mp4: Invalid argument

    at ChildProcess.<anonymous> (F:\Development\live-stream-radio\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)


ffmpeg encountered an error. 😨
Please see the stderror output above to fix the issue.
```

**Comment by torch2424** [comment]
My bad 😢

**Comment by AndreasWebdev** [comment]
I think we still need to escape the paths somehow, shown by this ffmpeg error output from my DO:

```
 ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/radio/splatoon-radio/video/dancev2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2018-10-07T11:57:32.000000Z
  Duration: 00:01:28.00, start: 0.000000, bitrate: 10348 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 10025 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2018-10-07T11:57:32.000000Z
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2018-10-07T11:57:33.000000Z
      handler_name    : Alias Data Handler
Input #1, mp3, from '/home/radio/splatoon-radio/audio/OctoTunes/Disc 1/1.27 The Real Commander Tartar's Theme.mp3':
  Metadata:
    title           : The Real Commander Tartar's Theme
    album           : Splatoon 2 ORIGINAL SOUNDTRACK -Octotune-
    publisher       : KADOKAWA
    genre           : Game Soundtrack
    RELEASE DATE    :   Jul 18, 2018
    track           : 27/52
    disc            : 1/2
    artist          : Ryo Nagamatsu
    album_artist    : KADOKAWA
    composer        : Ryo Nagamatsu
    comment         : http://sittingonclouds.net
    date            : 2018
  Duration: 00:00:39.18, start: 0.025056, bitrate: 336 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : LAME3.99r
    Stream #1:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x495 [SAR 28:28 DAR 100:99], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
Input #2, lavfi, from 'anullsrc':
  Duration: N/A, start: 0.000000, bitrate: 705 kb/s
    Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
Input #3, png_pipe, from '/home/radio/splatoon-radio/overlay.png':
  Duration: N/A, bitrate: N/A
    Stream #3:0: Video: png, rgba(pc), 1280x720 [SAR 2835:2835 DAR 16:9], 25 tbr, 25 tbn, 25 tbc
Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.

ffmpeg stdout:


ffmpeg err:

 Error: ffmpeg exited with code 1: Output with label 'videooutput' does not exist in any defined filter graph, or was already used elsewhere.

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/live-stream-radio/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)


ffmpeg encountered an error. 😨
Please see the stderror output above to fix the issue.

```

`Input #1, mp3, from '/home/radio/splatoon-radio/audio/OctoTunes/Disc 1/1.27 The Real Commander Tartar's Theme.mp3':`

Look, that file has an ' in it!

(For now I am renaming all filenames to azAZ09)

**Comment by torch2424** [comment]
Ahhh that would make sense. Yeah we really need safe strings, and context of when to use them 😢 

FFmpeg can be weird haha!

**Comment by AndreasWebdev** [comment]
i'm gonna close this issue as it referenced an already obsolete version
